### ISSUE TITLE
Make TA an `owner`

### ISSUE THREAD

**Issue by hugolpz** [PIB4-2022/Command-Cheatsheet#3]
- [x] Create github organization @PIB4-2022
- [x] Transfer current repository ownership from @whitecanarystan to @PIB4-2022<br>`Settings >Transfert ownership`
- [x] Assign @hugolpz @whitecanarystan, Octave, Maxime as co-owner (will be for few weeks)<br>`> Settings > Collaborators > invite : enter username`

**Comment by PurpleShad0w** [comment]
Done !
